// API utility for fetching emojis
// TODO: INSERT YOUR API NINJAS API KEY HERE
const API_KEY = "wLBJdBxQo/+mJen0VMYsZA==jwtCCpAhHs3HTQMt";
const BASE_URL = "https://api.api-ninjas.com/v1/emoji";

// Comprehensive fallback emoji map for all keywords
const COMPREHENSIVE_FALLBACK_EMOJIS = {
  // Original keywords
  wizard: "🧙‍♂️",
  ring: "💍",
  volcano: "🌋",
  spider: "🕷️",
  man: "👨",
  web: "🕸️",
  star: "⭐",
  wars: "⚔️",
  lightsaber: "⚡",
  bat: "🦇",
  gotham: "🏙️",
  iron: "🦾",
  arc: "🏹",
  harry: "👓",
  potter: "🏺",
  wand: "🪄",
  jedi: "⚔️",
  knight: "🤺",
  force: "💫",
  super: "🦸",
  krypton: "🪐",
  captain: "👨‍✈️",
  america: "🇺🇸",
  shield: "🛡️",
  thor: "⚡",
  hammer: "🔨",
  asgard: "🏰",

  // Sci-Fi keywords
  matrix: "💊",
  hacker: "💻",
  simulation: "🔄",
  avatar: "🔵",
  pandora: "🌿",
  blue: "🔷",
  interstellar: "🌌",
  space: "🚀",
  wormhole: "🌀",
  alien: "👽",
  bike: "🚲",
  moon: "🌙",
  replicant: "🤖",
  rain: "🌧️",
  neon: "💡",
  xenomorph: "👾",
  ship: "🚢",
  desert: "🏜️",
  spice: "🧂",
  worms: "🪱",
  time: "⏰",
  travel: "✈️",
  car: "🚗",
  robot: "🤖",
  cyborg: "🔧",
  future: "🔮",

  // Fantasy keywords
  hobbit: "🧝",
  dragon: "🐉",
  journey: "🗺️",
  wardrobe: "🚪",
  winter: "❄️",
  true: "✅",
  swashbuckler: "⚔️",
  faun: "🐐",
  maze: "🌀",
  war: "⚔️",
  sleep: "😴",
  horns: "🦄",
  creatures: "🐾",
  suitcase: "💼",
  rose: "🌹",
  castle: "🏰",
  fallen: "🍂",
  sky: "☁️",

  // Adventure keywords
  dinosaur: "🦕",
  island: "🏝️",
  park: "🎡",
  pirate: "🏴‍☠️",
  curse: "⚡",
  archaeologist: "🔍",
  whip: "🪢",
  temple: "🏛️",
  game: "🎲",
  jungle: "🌴",
  dice: "🎲",
  tomb: "⚰️",
  scarab: "🪲",
  map: "🗺️",
  liberty: "🗽",
  heist: "🦹",
  boy: "👦",
  wolves: "🐺",
  bear: "🐻",
  gorilla: "🦍",
  skyscraper: "🏢",
  tiger: "🐯",
  boat: "⛵",
  ocean: "🌊",
  treasure: "💎",
  kids: "👶",

  // Animation keywords
  frozen: "❄️",
  ice: "🧊",
  queen: "👑",
  aladdin: "🧞",
  genie: "🪔",
  lamp: "💡",
  lion: "🦁",
  king: "👑",
  savanna: "🌾",
  wakanda: "💎",
  panther: "🐆",
  guardians: "🛡️",
  galaxy: "🌌",
  mixtape: "📼",
  amazon: "🏹",
  warrior: "⚔️",
  lasso: "🪢",
  deadpool: "🔴",
  mercenary: "💰",
  red: "🔴",
  toys: "🧸",
  friendship: "🤝",
  cowboy: "🤠",
  fish: "🐠",
  clown: "🤡",
  ogre: "👹",
  swamp: "🐸",
  donkey: "🦙",
  emotions: "😊",
  mind: "🧠",
  joy: "😄",
  guitar: "🎸",
  skeleton: "💀",
  marigold: "🌼",
  balloons: "🎈",
  house: "🏠",
  old: "👴",
  rat: "🐀",
  chef: "👨‍🍳",
  paris: "🗼",

  // Action keywords
  mission: "🎯",
  spy: "🕵️",
  mask: "🎭",
  agent: "🕵️",
  "007": "🔫",
  martini: "🍸",
  tower: "🗼",
  christmas: "🎄",
  cop: "👮",
  chase: "🏃",
  rig: "🚛",
  hitman: "💀",
  dog: "🐕",
  revenge: "⚔️",
  amnesia: "🧠",
  passport: "📄",
  bus: "🚌",
  bomb: "💣",
  fast: "⚡",
  rome: "🏛️",
  arena: "⚔️",
  spartans: "🛡️",
  battle: "⚔️",
  persia: "🏺",
  boxer: "🥊",
  underdog: "🐕",
  training: "💪",

  // Thriller keywords
  inception: "🌙",
  dream: "💭",
  sins: "😈",
  serial: "📺",
  fbi: "🕵️",
  cannibal: "🍖",
  lotion: "🧴",
  asylum: "🏥",
  storm: "⛈️",
  marshal: "👮",
  kidnapping: "🚨",
  rivalry: "⚔️",
  trick: "🎭",
  rules: "📜",
  underground: "🚇",
  class: "📚",
  scheme: "🎭",
  camera: "📷",
  news: "📰",
  accident: "🚑",
  disappearance: "❓",
  marriage: "💒",
  media: "📺",
  soap: "🧼",
  book: "📚",
  monster: "👹",
  grief: "😢",
  sunken: "🌊",
  tea: "☕",
  chair: "🪑",
  haunted: "👻",
  demons: "😈",
  detective: "🕵️",
  london: "🇬🇧",
  violin: "🎻",

  // Comedy keywords
  thieves: "🦹",
  traps: "🪤",
  trickster: "🎭",
  green: "🟢",
  vegas: "🎰",
  tiger: "🐯",
  missing: "❓",
  teen: "👨‍🎓",
  party: "🎉",
  id: "🆔",
  friends: "👥",
  road: "🛣️",
  van: "🚐",
  nanny: "👩‍👶",
  disguise: "🎭",
  family: "👨‍👩‍👧‍👦",
  loop: "🔄",
  alarm: "⏰",
  weather: "🌤️",
  highschool: "🏫",
  burn: "🔥",
  drum: "🥁",
  bunk: "🛏️",
  boats: "⛵",
  zombie: "🧟",
  pub: "🍺",
  cricket: "🦗",

  // Romance keywords
  ship: "🚢",
  iceberg: "🧊",
  love: "❤️",
  jazz: "🎷",
  dance: "💃",
  hollywood: "🎬",
  letters: "💌",
  rain: "🌧️",
  lake: "🏞️",
  regency: "👑",
  proposal: "💍",
  singapore: "🇸🇬",
  wealth: "💰",
  bookshop: "📚",
  actress: "🎭",
  illness: "🤒",
  promise: "🤝",
  poem: "📝",
  bet: "💰",
  memory: "🧠",
  erase: "🧽",
  beach: "🏖️",
  cancer: "🦀",
  amsterdam: "🇳🇱",
  stars: "⭐",

  // Horror keywords
  balloon: "🎈",
  sewer: "🚽",
  nightmare: "😱",
  glove: "🧤",
  freddy: "🔪",
  tape: "📼",
  well: "🕳️",
  seven: "7️⃣",
  possession: "👹",
  priest: "⛪",
  pea: "🫛",
  cult: "👥",
  miniatures: "🏠",
  click: "🖱️",
  hotel: "🏨",
  twins: "👯",
  axe: "🪓",
  silence: "🤫",
  monsters: "👹",

  // Mystery keywords
  knife: "🔪",
  mansion: "🏰",
  journalist: "📰",
  case: "📁",
  train: "🚂",
  mustache: "👨",
  code: "🔐",
  killer: "🔪",
  symbols: "🔯",
  louvre: "🏛️",
  church: "⛪",
  kidnap: "🚨",
  boston: "🇺🇸",
  imprisoned: "🔒",
  octopus: "🐙",
  neighbor: "🏠",
  apartment: "🏢",

  // Classics keywords
  mafia: "🕴️",
  don: "👔",
  life: "💚",
  chocolates: "🍫",
  bench: "🪑",
  airport: "✈️",
  piano: "🎹",
  rosebud: "🌹",
  newspaper: "📰",
  tycoon: "💰",
  yellow: "🟡",
  witch: "🧙‍♀️",
  umbrella: "☂️",
  tap: "🚰",
  studio: "🎬",
  shower: "🚿",
  motel: "🏨",
  mother: "👩",
  angel: "👼",
  bells: "🔔",
  town: "🏘️",
  nuns: "👩‍💼",
  alps: "🏔️",
  songs: "🎵",
  rebellion: "⚔️",
  chief: "👨‍💼",

  // Sports keywords
  football: "🏈",
  coach: "📋",
  unity: "🤝",
  basketball: "🏀",
  grades: "📊",
  baseball: "⚾",
  stats: "📈",
  oakland: "🌉",
  crane: "🦩",
  dojo: "🏯",
  wax: "🕯️",
  corn: "🌽",
  ghosts: "👻",
  build: "🏗️",
  notre: "⛪",
  tunes: "🎵",
  legacy: "👑",
  adonis: "💪",
  left: "⬅️",
  olympics: "🏅",
  running: "🏃",
  chariot: "🏺",
};

// Fetch emoji for a given keyword
export const fetchEmoji = async (keyword) => {
  try {
    const response = await fetch(
      `${BASE_URL}?name=${encodeURIComponent(keyword)}`,
      {
        headers: {
          "X-Api-Key": API_KEY,
        },
      }
    );

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    // Return the first emoji found, or a fallback
    if (data && data.length > 0) {
      return data[0].character;
    }

    // Return comprehensive fallback emoji
    return COMPREHENSIVE_FALLBACK_EMOJIS[keyword.toLowerCase()] || "❓";
  } catch (error) {
    console.error("Error fetching emoji:", error);

    // Return comprehensive fallback emoji on error
    return COMPREHENSIVE_FALLBACK_EMOJIS[keyword.toLowerCase()] || "❓";
  }
};

// Fetch emojis for multiple keywords
export const fetchEmojisForKeywords = async (keywords) => {
  const emojiPromises = keywords.map((keyword) => fetchEmoji(keyword));
  const emojis = await Promise.all(emojiPromises);
  return emojis;
};
